version: '3.9'

services:
  load-balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    ports:
      - 9000:80
    depends_on:
      - api-1
      - api-2
      - api-3
  api-1:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9001:80
    volumes:
      - /Users/kamila/Desktop/Computer Science/Large Systems:/data
  api-2:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9002:80
    volumes:
      - /Users/kamila/Desktop/Computer Science/Large Systems:/data
  api-3:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9003:80
    volumes:
      - /Users/kamila/Desktop/Computer Science/Large Systems:/data
  web-1:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9011:80