version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - 9000:80
    volumes:
      - /Users/kamila/Desktop/Computer Science/Large Systems:/data